/// Identifier. Paper Document Number. Numeric, from 1 to 6 digits.
/// Создано из: /backup/cbrf/XMLSchemas-2-1/ed/cbr_ed_leaftypes_v2019.2.0.xsd
Class Sb.xsd.lt.AccountDocIDType Extends Sb.xsd.bt.IdentifierCategory [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter MAXLEN = 6;

Parameter MINLEN = 1;

Parameter NAMESPACE = "urn:cbr-ru:ed:leaftypes:v2.0";

Parameter XMLPATTERN = "[0-9]*[1-9][0-9]*";

}

