/// Quantity. Number of documents (elements of documents) not certified controller. Integer, up to 5 digits.
/// Создано из: /backup/cbrf/XMLSchemas-2-1/ed/cbr_ed_leaftypes_v2019.2.0.xsd
Class Sb.xsd.lt.ErrorEDQuantityType Extends Sb.xsd.bt.QuantityCategory [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "urn:cbr-ru:ed:leaftypes:v2.0";

Parameter XMLTotalDigits = 5;

}

