/// Text. String type pain.xxx.xxx.xx or camt.xxx.xxx.xx, where x - only number.
/// Создано из: /backup/cbrf/XMLSchemas-2-1/ed/cbr_ed_leaftypes_v2019.2.0.xsd
Class Sb.xsd.lt.ISOTextType Extends Sb.xsd.bt.TextCategory [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "urn:cbr-ru:ed:leaftypes:v2.0";

Parameter XMLPATTERN = "([p][a][i][n]|[c][a][m][t])[.]([0-9]{3})[.]([0-9]{3})[.]([0-9]{2})";

}

