/// Code. Queuing Reason Code. Text, 4 characters.
/// Создано из: /backup/cbrf/XMLSchemas-2-1/ed/cbr_ed_leaftypes_v2019.2.0.xsd
Class Sb.xsd.lt.QueuingReasonCodeType Extends Sb.xsd.bt.CodeCategory [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "urn:cbr-ru:ed:leaftypes:v2.0";

Parameter VALUELIST = ",QLLQ,QWFC,QLSF,QLSV,QLIF,QLIV,QCLI,QICL,QTCL,QLRS,QLRW,QIRS,QACI,QCES,QNET";

}

