/// Сумма. В сотых долях валюты (для обозначения неотрицательной суммы). Положительное целое число или ноль, до 18 разрядов.
/// Создано из: /backup/cbrf/XMLSchemas-2-1/ed/cbr_ed_leaftypes_v2019.2.0.xsd
Class Sb.xsd.lt.NotNegativeCurrencyAmountType Extends Sb.xsd.bt.AmountCategory [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "urn:cbr-ru:ed:leaftypes:v2.0";

Parameter XMLTotalDigits = 18;

}

