/// Курс валюты. Цена денежной единицы одной страны, выраженная в денежных единицах другой страны. Числовая информация, определенная последовательностью положительных чисел с десятичной дробной частью.
/// Создано из: /backup/cbrf/XMLSchemas-2-1/ed/cbr_ed_basetypes_v2018.3.0.xsd
Class Sb.xsd.bt.CurrencyCategory Extends %Numeric [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "urn:cbr-ru:ed:basetypes:v2.0";

}

