Class appmsw.banks.production Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="appmsw.banks.production" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="appmsw.banks.service" Category="" ClassName="appmsw.banks.service" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}

