/// Количество. Счетное количество неденежных единиц. Количество представляется с заданными по умолчанию единицами измерения.
/// Создано из: /backup/cbrf/XMLSchemas-2-1/ed/cbr_ed_basetypes_v2018.3.0.xsd
Class Sb.xsd.bt.QuantityCategory Extends %Integer [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "urn:cbr-ru:ed:basetypes:v2.0";

Parameter XMLPATTERN = "[\-]?[1-9]\d{0,}|[0]";

}

